on:
  push:
  workflow_dispatch: # Manual Input
  schedule:
    - cron: "23 1 * * 4" # 01:23 every Thursday
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Deploy Site
        run: ./vercel-build.sh
